Updated packages, updated dockerfiles, added more utilities
i-dot-ai/cookie-cutter pull request #1
Opened 2023-07-05 12:49 UTC by 252afh

2023-07-11 10:29 UTC, Singletoned requested changes

2023-07-11 10:29 UTC, Singletoned commented on {{cookiecutter.project_slug}}/docker/tests/entrypoint.sh
> +timeout 60s bash -c "until pg_isready -d $DATABASE_URL; do sleep 5; done"
We should probably be using `wait-for-db` here

2023-07-11 10:29 UTC, Singletoned commented on {{cookiecutter.project_slug}}/{{cookiecutter.package_name}}/jinja2.py
> +    html = html.replace("<p>", f'<p class="{cls or ""}">', 1).replace("</p>", "", 1)
What is this supposed to be doing?  We probably need a docstring or comment in here to explain (or remove this line)

2023-07-11 10:29 UTC, Singletoned commented
I think we probably don't need the PaaS deploy and proxy files in there

2023-07-11 12:41 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/.github/workflows/proxy.yml
> +      - uses: actions/checkout@v2
Let's get rid of the Slack Notifications - no-one uses them, and some of us don't understand them.

2023-07-11 12:43 UTC, nmenezes0 commented
Please can you add a README with instructions on how to generate a new cookiecutter project?

2023-07-11 12:49 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/.github/workflows/checks.yml
> +    - name: Set up Python 3.9
3.9 or 3.8?
Maybe 3.9? (I think has to be <=3.9 for Notify?)

2023-07-11 12:50 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/.github/workflows/checks.yml
> +    - name: Set up Python 3.9
3.8 definitely referenced elsewhere

2023-07-11 12:56 UTC, nmenezes0 commented
Got an error when trying to run:
```
Traceback (most recent call last):
  File "/Users/nina.menezes/.virtualenvs/testenv/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/cookiecutter/cli.py", line 194, in main
    cookiecutter(
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/cookiecutter/main.py", line 114, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/cookiecutter/generate.py", line 373, in generate_files
    generate_file(
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/cookiecutter/generate.py", line 173, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/nina.menezes/.virtualenvs/testenv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File ".github/workflows/proxy.yml", line 89, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '&' at 2481
  File ".github/workflows/proxy.yml", line 89
    if: ${{ failure() && github.ref_name == 'prod' || failure() && github.ref_name == 'develop' }}
```

Might be ok once the `proxy` stuff is removed.

2023-07-11 12:57 UTC, nmenezes0 requested changes
Looks good overall, a couple of minor comments, I'd like to make sure I can get it to run before approving.

2023-07-13 13:05 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/README.md
> +    make check-python-code
Add some stuff on using the cookiecutter, which as I recall was something like installing python package, cloning this repo, running some command like `cookiecutter cookie-cutter`.

2023-07-13 13:10 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/README.md
> +    make check-python-code
DOh, it was in the actual readme.
Just ignore me

2023-07-13 14:45 UTC, nmenezes0 approved these changes
All runs fine for me now - this is going to be really helpful for the next urgent project!

2023-07-18 18:44 UTC, nmenezes0 requested changes
One comment on making markdown safe

2023-07-18 18:44 UTC, nmenezes0 commented on {{cookiecutter.project_slug}}/{{cookiecutter.package_name}}/jinja2.py
> +markdown_converter = MarkdownIt()
Change to `MarkdownIt("js-default")` to make it safe.
https://markdown-it-py.readthedocs.io/en/latest/security.html for background

2023-07-20 09:37 UTC, nmenezes0 approved these changes
Subject also to Ed's approval!

2023-08-11 07:43 UTC, Singletoned approved these changes

2023-08-11 07:43 UTC, merged